---
- user: ubuntu
  hosts: all
  become: true
  gather_facts: true

  vars:
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - ansible_port: "22"
    - ENVIRONMENT: "production"
    - TYPEORM_MIGRATIONS: "./src/migrations/*.ts"
    - TYPEORM_MIGRATIONS_DIR: "./src/migrations"
    - TYPEORM_CONNECTION: "postgres"
    - TYPEORM_ENTITIES: "./src/modules/domain/**/*.entity.ts"
    - TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    - TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    - TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    - TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    - TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"

    - name: "install python for Ansible."
      become: true
      raw: 'sudo apt-get -y install python3'

  roles:
    - deploy
